name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test2_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: dotnet test -f netcoreapp2.1
      
  test3_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: dotnet test -f netcoreapp3.1

  test4_5:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: dotnet test -f net45
